### ISSUE TITLE
Add More Languages

### ISSUE THREAD

**Issue by Koslas1** [Bwana-Ian/OSRSParaTodos#2]
I speak English, but have been learning a bit of German. I'd love it if you could add a drop down box in the plugin settings to chose what language you'd want the game translated to, and let me know what id need to do exactly to help translate part of the game.

**Comment by Bwana-Ian** [comment]
I will work on this project some more on monday most likely. Ill get something set up so its easier to make new languages to be added. Thanks for the interest in the plugin!

**Comment by Bwana-Ian** [comment]
I have added German, French, and a broken Russian. Once the PR is approved by Runelite you should see them added.
